version: "3.9"
   
services:
  dev:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    working_dir: /workspace
    volumes: 
      - ./:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
